export const LOAD_BOOK_LIST = 'LOAD_BOOK_LIST';
export const UNMOUNT_LOAD_BOOK_LIST = 'UNMOUNT_LOAD_BOOK_LIST';
export const LOAD_BOOK_DETAILS = 'LOAD_BOOK_DETAILS';
export const UNMOUNT_BOOK_DETAILS = 'UNMOUNT_BOOK_DETAILS';
export const USER_BOOK_LIST = 'USER_BOOK_LIST';
export const UNMOUNT_USER_BOOK_LIST = 'UNMOUNT_USER_BOOK_LIST';
export const BOOK_CREATION = 'BOOK_CREATION';
export const UNMOUNT_BOOK_CREATION = 'UNMOUNT_BOOK_CREATION';
export const GET_BOOK = 'GET_BOOK';
export const BOOK_UPDATE = 'BOOK_UPDATE';
export const UNMOUNT_BOOK_VALUES = 'UNMOUNT_BOOK_VALUES';
export const UNMOUNT_EDIT_FORM = 'UNMOUNT_EDIT_FORM';

export const LOADNEWBOOK = 'LOADNEWBOOK';

export const BOOK_DELETE = 'BOOK_DELETE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const UNMOUNT_LOGIN = 'UNMOUNT_LOGIN';

export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAIL = 'SIGNUP_USER_FAIL';
export const UNMOUNT_SIGNUP = 'UNMOUNT_SIGNUP';

export const AUTH_LOGOUT= 'AUTH_LOGOUT';

export const LOAD_USER_PROFILE = 'LOAD_USER_PROFILE';
export const UNMOUNT_LOAD_USER_PROFILE = 'UNMOUNT_LOAD_USER_PROFILE';
